
set(PACKAGE_VERSION "3.1.0")

if ("${PACKAGE_FIND_VERSION_MAJOR}" EQUAL "3")
	set(PACKAGE_VERSION_COMPATIBLE TRUE)
	if ("${PACKAGE_FIND_VERSION_MINOR}" EQUAL 1)
		set(PACKAGE_VERSION_EXACT TRUE)
	endif()
else()
	set(PACKAGE_VERSION_COMPATIBLE FALSE)
endif()

